import os
import mmap
import json
import pickle
import ijson
import torch
from torch.utils.data import Dataset, DataLoader
from config import config


def _build_json_offset_index(file_path):
    import re
    offsets = []
    with open(file_path, "rb") as f:
        raw = f.read()

    depth      = 0
    in_string  = False
    escape     = False
    item_start = None
    i          = 0
    while i < len(raw):
        b = raw[i:i+1]
        if escape:
            escape = False
        elif in_string:
            if b == b'\\':
                escape = True
            elif b == b'"':
                in_string = False
        else:
            if b == b'"':
                in_string = True
            elif b == b'{':
                if depth == 1:
                    item_start = i
                depth += 1
            elif b == b'}':
                depth -= 1
                if depth == 1 and item_start is not None:
                    offsets.append(item_start)
                    item_start = None
            elif b == b'[':
                depth += 1
            elif b == b']':
                depth -= 1
        i += 1
    return offsets


class _StreamingPlaceholder:
    def __init__(self, count, filepath):
        self._count    = count
        self._filepath = filepath
        self._file     = open(filepath, "rb")
        self._mmap     = mmap.mmap(self._file.fileno(), 0, access=mmap.ACCESS_READ)

    def __len__(self):
        return self._count

    def __del__(self):
        try:
            if hasattr(self, "_mmap") and self._mmap:
                self._mmap.close()
            if hasattr(self, "_file") and self._file:
                self._file.close()
        except Exception:
            pass

    def read_at(self, offset):
        mm    = self._mmap
        depth = 0
        in_string = False
        escape    = False
        i         = offset
        n         = len(mm)
        while i < n:
            b = mm[i:i+1]
            if escape:
                escape = False
            elif in_string:
                if b == b"\\":
                    escape = True
                elif b == b'"':
                    in_string = False
            else:
                if b == b'"':
                    in_string = True
                elif b in (b"{", b"["):
                    depth += 1
                elif b in (b"}", b"]"):
                    depth -= 1
                    if depth == 0:
                        return json.loads(mm[offset:i+1])
            i += 1
        raise ValueError(f"Incomplete JSON object at offset {offset}")


class TensorPtDataset(Dataset):
    """
    Fast dataset loading pre-processed tensors from a .pt file.
    Generated by: python preprocess_dataset.py
    Activated by: config["file_format"] = "tensor_pt"

    NOTE: .pt files are keyed to a specific feature_size.  If you change
    feature toggles you MUST re-run preprocess_dataset.py (or delete the
    .pt files so they are regenerated on next startup).
    """
    def __init__(self, pt_path):
        if not os.path.exists(pt_path):
            raise FileNotFoundError(
                f"Pre-processed .pt file not found: {pt_path}\n"
                f"Run: python preprocess_dataset.py"
            )
        print(f"--> Loading tensor dataset: {pt_path}")
        self._samples = torch.load(pt_path, weights_only=False)
        print(f"<-- Loaded {len(self._samples):,} samples from {pt_path}\n")

        # ── Feature-column selection ─────────────────────────────────────────
        use_dxdy = bool(config.get("feature_dx_dy", False))
        use_f6   = bool(config.get("feature_free_neighbours", False))
        use_f7   = bool(config.get("feature_is_interior", False))
        col_idx = [0, 1, 2, 3]
        if use_dxdy:
            col_idx += [4, 5]
        if use_f6:
            col_idx += [6]
        if use_f7:
            col_idx += [7]

        if self._samples and "input_tensor" in self._samples[0]:
            pt_width = int(self._samples[0]["input_tensor"].shape[-1])
            need     = max(col_idx) + 1
            if pt_width < need:
                raise ValueError(
                    f"[DATALOADER] .pt file has feature_size={pt_width}, but the "
                    f"active feature toggles need column {max(col_idx)} "
                    f"(feature_size={len(col_idx)}).\n"
                    f"Regenerate the dataset with all 8 features (A* generator), "
                    f"or turn the extra feature toggles off."
                )
            if pt_width != len(col_idx):
                _cols = torch.as_tensor(col_idx, dtype=torch.long)
                for s in self._samples:
                    it = s.get("input_tensor")
                    if it is not None and it.shape[-1] >= need:
                        s["input_tensor"] = it.index_select(-1, _cols)
                print(f"--> Selected feature columns {col_idx} "
                      f"(feature_size={len(col_idx)}) from {pt_width}-wide tensors\n")

    def __len__(self):
        return len(self._samples)

    def __getitem__(self, idx):
        s            = self._samples[idx]
        input_tensor = s["input_tensor"]
        context = s.get("Context", s.get("context", None))
        if context is None:
            context = self._reconstruct_context(input_tensor)

        # Found_Routes: use stored list if present (including empty [] for nosol).
        # Only reconstruct from input_tensor when the key is genuinely absent.
        found_routes = s.get("Found_Routes", s.get("found_routes", None))
        if found_routes is None:
            found_routes = self._reconstruct_found_routes(input_tensor)

        return (
            input_tensor,
            s["masking_tensor"],
            s["target_tensor"],
            context,
            found_routes,
        )

    def _reconstruct_context(self, input_tensor):
        """Rebuild context cell-dict list from the context slice of input_tensor."""
        from config import config as _cfg
        context_len  = int(_cfg["context_matrix_length"])
        padding_val  = float(_cfg["padding_value"])
        fidx_cell    = int(_cfg["fidx_cell_num"])
        fidx_x       = int(_cfg["fidx_x"])
        fidx_y       = int(_cfg["fidx_y"])
        fidx_st      = int(_cfg["fidx_status"])
        context = []
        for i in range(context_len):
            cn = input_tensor[i, fidx_cell].item()
            if cn == padding_val or cn <= 0:
                continue
            context.append({
                "Cell_Number":  int(cn),
                "x":            int(input_tensor[i, fidx_x].item()),
                "y":            int(input_tensor[i, fidx_y].item()),
                "State_Status": int(input_tensor[i, fidx_st].item()),
            })
        return context

    def _reconstruct_found_routes(self, input_tensor):
        """Rebuild found_routes cell-dict list from the latent slice of input_tensor."""
        from config import config as _cfg
        context_len = int(_cfg["context_matrix_length"])
        seq_len     = input_tensor.shape[0]
        padding_val = float(_cfg["padding_value"])
        fidx_cell   = int(_cfg["fidx_cell_num"])
        fidx_x      = int(_cfg["fidx_x"])
        fidx_y      = int(_cfg["fidx_y"])
        fidx_st     = int(_cfg["fidx_status"])
        found_routes = []
        for i in range(context_len, seq_len):
            cn = input_tensor[i, fidx_cell].item()
            if cn == padding_val or cn <= 0:
                break
            found_routes.append({
                "Cell_Number":  int(cn),
                "x":            int(input_tensor[i, fidx_x].item()),
                "y":            int(input_tensor[i, fidx_y].item()),
                "State_Status": int(input_tensor[i, fidx_st].item()),
            })
        return found_routes


class PathfindingDataset(Dataset):
    def __init__(self, file_path, config, pickle_key=None):
        self.config    = config
        self.file_path = file_path
        self.samples   = []
        file_format    = config.get("file_format", "pickle")
        data_streaming = bool(config.get("data_streaming", False))
        pickle_path    = config.get(pickle_key) if pickle_key else file_path.replace(".json", ".pkl")

        pt_path = file_path.replace(".json", ".pt")
        if file_format == "tensor_pt" and os.path.exists(pt_path):
            self._pt_dataset = TensorPtDataset(pt_path)
            self.samples     = self._pt_dataset._samples
            self._use_pt     = True

        elif file_format == "pickle" and os.path.exists(pickle_path):
            print(f"--> Loading pickle file: {pickle_path}")
            with open(pickle_path, "rb") as f:
                self.samples = pickle.load(f)
            print(f"<-- DataLoaded {len(self.samples)} samples from {pickle_path} (pickle) into memory\n")
            self._use_pt = False

        elif data_streaming:
            idx_path = file_path + ".idx"
            if os.path.exists(idx_path):
                print(f"--> Loading offset index: {idx_path}")
                with open(idx_path, "rb") as _f:
                    self._offsets = pickle.load(_f)
                print(f"<-- Offset index loaded: {len(self._offsets)} samples\n")
            else:
                print(f"--> Building offset index for: {file_path}")
                print(f"    (one-time scan — saved to {idx_path} for future runs)")
                self._offsets = _build_json_offset_index(file_path)
                with open(idx_path, "wb") as _f:
                    pickle.dump(self._offsets, _f)
                print(f"<-- Offset index built: {len(self._offsets)} samples\n")
            self.samples = _StreamingPlaceholder(len(self._offsets), file_path)

        else:
            print(f"--> Loading JSON file: {file_path}")
            with open(file_path, "r") as f:
                for sample in ijson.items(f, "item"):
                    self.samples.append(sample)
            print(f"<-- DataLoaded {len(self.samples)} samples from {file_path} (JSON) into memory\n")

        self.length                  = len(self.samples)
        self.grid_size               = config["grid_size"]
        self.feature_size            = config["feature_size"]
        self.context_matrix_length   = config["context_matrix_length"]
        self.foundroute_matrix_length = config["foundroute_matrix_length"]
        self.target_matrix_length    = config["target_matrix_length"]
        self.padding_value           = config["padding_value"]

        if bool(self.config.get("dataset_integrity_check", False)):
            self._validate_samples()

    def _validate_samples(self):
        sample_size   = int(self.config.get("dataset_integrity_sample_size", 5))
        sample_size   = max(1, min(sample_size, self.length))
        padding_value = self.padding_value

        empty_found_routes = 0
        empty_targets      = 0

        for i in range(sample_size):
            sample       = self.samples[i]
            found_routes = sample.get("Found_Routes", [])
            targets      = sample.get("Targets", [])

            has_route = any(
                cell.get("Cell_Number", padding_value) != padding_value
                for cell in found_routes
                if isinstance(cell, dict)
            )
            if not has_route:
                empty_found_routes += 1

            has_target = any(
                t.get("target_vec") is not None and
                not all(v == padding_value for v in t.get("target_vec", []))
                for t in targets
                if isinstance(t, dict)
            )
            if not has_target:
                empty_targets += 1

        print(
            f"[DATASET CHECK] samples={sample_size} "
            f"empty_found_routes={empty_found_routes} "
            f"empty_targets={empty_targets}"
        )

    def __len__(self):
        return self.length

    def _build_feature_vec(self, cell_num, x, y, status,
                           dx_to_goal, dy_to_goal, f6, f7,
                           pad):
        """
        Return a Python list of floats with length == self.feature_size,
        respecting the active feature toggles from config.
        """
        use_dxdy = bool(self.config.get("feature_dx_dy",           False))
        use_f6   = bool(self.config.get("feature_free_neighbours",  False))
        use_f7   = bool(self.config.get("feature_is_interior",      False))

        vec = [float(cell_num), float(x), float(y), float(status)]  # f0-f3 always
        if use_dxdy:
            vec.append(float(dx_to_goal))  # f4
            vec.append(float(dy_to_goal))  # f5
        if use_f6:
            vec.append(float(f6))          # f6
        if use_f7:
            vec.append(float(f7))          # f7
        return vec

    def __getitem__(self, idx):
        # ── Fast path: pre-processed .pt tensors ──
        if getattr(self, "_use_pt", False):
            return self._pt_dataset[idx]

        # ── Streaming or bulk-loaded JSON ──
        if isinstance(self.samples, _StreamingPlaceholder):
            offset = self._offsets[idx]
            sample = self.samples.read_at(offset)
        else:
            sample = self.samples[idx]

        context      = sample.get('Context', [])
        found_routes = sample.get('Found_Routes', [])
        target       = sample.get('Targets', [])
        masking_data = sample.get('Masking', [])

        pad           = float(self.padding_value)
        padding_value = self.padding_value

        # -- STEP 1: Find goal position from context --
        goal_x, goal_y = None, None
        status_end     = self.config["status_end"]

        for cell in context:
            cell_num = cell.get('Cell_Number', padding_value)
            x        = cell.get('x', padding_value)
            y        = cell.get('y', padding_value)
            if cell_num == padding_value or x == padding_value or y == padding_value:
                continue
            if cell.get('State_Status') == status_end:
                goal_x = x
                goal_y = y
                break

        if goal_x is None or goal_y is None:
            for cell in context:
                cell_num = cell.get('Cell_Number', padding_value)
                x        = cell.get('x', padding_value)
                y        = cell.get('y', padding_value)
                if cell_num == padding_value or x == padding_value or y == padding_value:
                    continue
                goal_x = x
                goal_y = y
                break

        if goal_x is None or goal_y is None:
            goal_x = 1
            goal_y = 1

        # -- STEP 1b: Precompute f6/f7 only when their toggles are active --
        use_dxdy = bool(self.config.get("feature_dx_dy",           False))
        use_f6   = bool(self.config.get("feature_free_neighbours",  False))
        use_f7   = bool(self.config.get("feature_is_interior",      False))

        n_rows, n_cols  = self.grid_size
        max_neighbours  = float(self.config.get("max_neighbours", 4))
        status_obstacle = self.config["status_obstacle"]

        obstacle_cells = set()
        if use_f6 or use_f7:
            for cell in context:
                if cell.get("State_Status") == status_obstacle:
                    cn = cell.get("Cell_Number", padding_value)
                    if cn != padding_value:
                        obstacle_cells.add(cn)

        def _compute_f6_f7(cell_num):
            if cell_num == padding_value:
                return 0.0, 0.0
            row = (cell_num - 1) // n_cols
            col = (cell_num - 1) % n_cols
            free_count = 0
            has_oob    = False
            for dr, dc in ((-1, 0), (1, 0), (0, 1), (0, -1)):
                r, c = row + dr, col + dc
                if not (0 <= r < n_rows and 0 <= c < n_cols):
                    has_oob = True
                elif r * n_cols + c + 1 not in obstacle_cells:
                    free_count += 1
            f6 = (free_count / max_neighbours) if use_f6 else 0.0
            f7 = (0.0 if has_oob else 1.0)    if use_f7 else 0.0
            return f6, f7

        cell_features_67 = {}
        if use_f6 or use_f7:
            for cell in context:
                cn = cell.get("Cell_Number", padding_value)
                if cn == padding_value:
                    continue
                # Prefer values baked onto the Context dict; else compute.
                if ("free_neighbours" in cell) or ("is_interior" in cell):
                    f6 = float(cell.get("free_neighbours", 0.0)) if use_f6 else 0.0
                    f7 = float(cell.get("is_interior", 0.0))     if use_f7 else 0.0
                    cell_features_67[cn] = (f6, f7)
                else:
                    cell_features_67[cn] = _compute_f6_f7(cn)

        # -- STEP 2: Context matrix --
        context_matrix = torch.full(
            (self.context_matrix_length, self.feature_size), pad, dtype=torch.float32
        )
        for i, cell in enumerate(context):
            if i >= self.context_matrix_length:
                break
            cell_num = cell.get('Cell_Number', padding_value)
            x        = cell.get('x', padding_value)
            y        = cell.get('y', padding_value)
            status   = cell.get('State_Status', self.config["status_free"])

            is_pad_cell = (cell_num == padding_value or
                           x == padding_value or y == padding_value)
            if not is_pad_cell:
                dx_to_goal = float(cell.get("dx_to_goal", goal_x - x)) if use_dxdy else 0.0
                dy_to_goal = float(cell.get("dy_to_goal", goal_y - y)) if use_dxdy else 0.0
            else:
                dx_to_goal = pad if use_dxdy else 0.0
                dy_to_goal = pad if use_dxdy else 0.0

            f6, f7 = (cell_features_67.get(cell_num, (0.0, 0.0))
                      if not is_pad_cell else (pad, pad))

            vec = self._build_feature_vec(
                cell_num, x, y, status,
                dx_to_goal, dy_to_goal, f6, f7, pad
            )
            context_matrix[i] = torch.tensor(vec, dtype=torch.float32)

        # -- STEP 3: Found-routes matrix --
        foundroute_matrix = torch.full(
            (self.foundroute_matrix_length, self.feature_size), pad, dtype=torch.float32
        )
        for i, cell in enumerate(found_routes):
            if i >= self.foundroute_matrix_length:
                break
            cell_num = cell.get('Cell_Number', padding_value)
            x        = cell.get('x', padding_value)
            y        = cell.get('y', padding_value)
            status   = cell.get('State_Status', self.config["status_free"])

            is_pad_cell = (cell_num == padding_value or
                           x == padding_value or y == padding_value)
            if not is_pad_cell:
                dx_to_goal = float(cell.get("dx_to_goal", goal_x - x)) if use_dxdy else 0.0
                dy_to_goal = float(cell.get("dy_to_goal", goal_y - y)) if use_dxdy else 0.0
            else:
                dx_to_goal = pad if use_dxdy else 0.0
                dy_to_goal = pad if use_dxdy else 0.0

            f6, f7 = (cell_features_67.get(cell_num, (0.0, 0.0))
                      if not is_pad_cell else (pad, pad))

            vec = self._build_feature_vec(
                cell_num, x, y, status,
                dx_to_goal, dy_to_goal, f6, f7, pad
            )
            foundroute_matrix[i] = torch.tensor(vec, dtype=torch.float32)

        input_tensor = torch.cat([context_matrix, foundroute_matrix], dim=0)

        num_directions = int(self.config.get("num_unique_tokens", 4))

        # -- STEP 4: Masking --
        masking_tensor = torch.full(
            (self.foundroute_matrix_length, num_directions), pad, dtype=torch.float32
        )
        for i, mask_entry in enumerate(masking_data):
            if i >= self.foundroute_matrix_length:
                break
            mask_vec = mask_entry.get("mask_vec", [padding_value] * num_directions)
            masking_tensor[i] = torch.tensor(mask_vec, dtype=torch.float32)

        # -- STEP 5: Targets --
        target_tensor = torch.full(
            (self.target_matrix_length, num_directions), pad, dtype=torch.float32
        )
        for i, cell in enumerate(target):
            if i >= self.target_matrix_length:
                break
            target_vec = cell.get("target_vec", [padding_value] * num_directions)
            target_tensor[i] = torch.tensor(target_vec, dtype=torch.float32)

        # -- Integrity checks --
        padding_value_f = float(self.padding_value)

        mask_has_pad = masking_tensor.eq(padding_value_f).any(dim=-1)
        assert (mask_has_pad == masking_tensor.eq(padding_value_f).all(dim=-1)).all(), \
            "Invalid Masking row: mixed padding values."

        target_has_pad = target_tensor.eq(padding_value_f).any(dim=-1)
        assert (target_has_pad == target_tensor.eq(padding_value_f).all(dim=-1)).all(), \
            "Invalid Target row: mixed padding values."

        real_mask_rows = ~mask_has_pad
        if real_mask_rows.any():
            assert (masking_tensor[real_mask_rows].eq(1).any(dim=-1)).all(), \
                "Invalid Masking row: real step has no allowed actions."

        real_target_rows = ~target_has_pad
        if real_target_rows.any():
            assert (target_tensor[real_target_rows].sum(dim=-1).eq(1)).all(), \
                "Invalid Target row: target_vec must be one-hot."

        return input_tensor, masking_tensor, target_tensor, context, found_routes


def collate_fn(batch):
    input_tensors, masking_tensors, target_tensors, contexts, found_routes_list = zip(*batch)
    return (
        torch.stack(input_tensors),
        torch.stack(masking_tensors),
        torch.stack(target_tensors),
        contexts,
        found_routes_list
    )

class RAGatePtDataset(Dataset):
    """
    Dataset for the RAGate .pt files (formerly RAGate_*.pt).
    Each sample must have keys:
      input_tensor, masking_tensor, target_tensor, label
    And optionally:
      Context / context, Found_Routes / found_routes

    Returns a 6-tuple:
      (input_tensor, masking_tensor, target_tensor, label, context, found_routes)
    """
    def __init__(self, pt_path):
        if not os.path.exists(pt_path):
            raise FileNotFoundError(
                f"RAGate .pt file not found: {pt_path}\n"
                f"Generate it with the A* dataset-generation repo and copy Datasets/RAGate/ here."
            )
        print(f"--> Loading RAGate dataset: {pt_path}")
        self._samples = torch.load(pt_path, weights_only=False)
        print(f"<-- Loaded {len(self._samples):,} RAGate samples from {pt_path}\n")

    def __len__(self):
        return len(self._samples)

    def __getitem__(self, idx):
        s = self._samples[idx]
        context     = s.get("Context",     s.get("context",     []))
        found_routes= s.get("Found_Routes",s.get("found_routes",[]))
        label       = int(s.get("label", -1))
        return (
            s["input_tensor"],
            s["masking_tensor"],
            s["target_tensor"],
            label,
            context,
            found_routes,
        )

    def get_raw(self, idx):
        """Return the full raw sample dict — used by UNIFIED visualisation."""
        return self._samples[idx]


def ragate_collate_fn(batch):
    input_tensors, masking_tensors, target_tensors, labels, contexts, found_routes_list = zip(*batch)
    return (
        torch.stack(input_tensors),
        torch.stack(masking_tensors),
        torch.stack(target_tensors),
        list(labels),
        contexts,
        found_routes_list,
    )


def get_ragate_dataloader(pt_path, config, shuffle=False):
    """
    Build a DataLoader for the RAGate .pt dataset.

    Returns (dataloader, dataset) — the dataset is returned separately so
    callers can use dataset.get_raw(idx) for visualisation entries.
    """
    dataset = RAGatePtDataset(pt_path)
    loader  = DataLoader(
        dataset,
        batch_size=config.get("ragate_embeddings_batch_size", 128),
        shuffle=shuffle,
        collate_fn=ragate_collate_fn,
        num_workers=0,           # RAGate is loaded entirely in memory
        pin_memory=config.get("pin_memory", False),
    )
    return loader, dataset


def get_dataloader(file_path, config, pickle_key=None, base_dataset=None):
    ds = base_dataset or PathfindingDataset(file_path, config, pickle_key)
    return DataLoader(
        ds,
        batch_size=config["batch"],
        shuffle=config.get("shuffle", False),
        collate_fn=collate_fn,
        num_workers=config.get("num_workers", 0),
        pin_memory=config.get("pin_memory", False)
    )
